send_to: 'backup_admin@company.com'
# email address for backup report

send_to_name: 'Backup Operators'
# email recipients name, doesn't really matter

email_server: 'smtp.company.com'
# email server address

send_from: 'backups@company.com'
# sender email address

send_from_name: 'Backup Server'
# email sender name

rsync_username: 'rsyncuser1'
# username for the rsync server
# the password should be a single line of just the password, saved in the
# config directory in a file named rsync_password.file.

backup_source_computer: 'server1.company.com'

backup_destination: '/mnt/btr_pool/files_share_backup/'
# where the backup will be copied to, and snapshots taken of
# this should be a subvolume of a btrfs volume.
